### PR TITLE
Update ch02

### PR DESCRIPTION
**Pull request by waddlaw**
- Update expression syntax (refer to [Expression](https://github.com/ucsd-progsys/liquidhaskell#expressions))
- FIx typo
- Change `UNSAFE` to `SAFE`

I think that I want to change to SAFE for all the chapters.
What do you think?

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Unfortunately we can't change the code blocks to hs blocks because the code
blocks are used to generate the online web demo ... :)

**Comment by waddlaw** [comment]
@ranjitjhala Oops. I didn't know that at all!

Online web demo is this?
- web: http://ucsd-progsys.github.io/liquidhaskell-tutorial/
- source code: https://github.com/ucsd-progsys/liquidhaskell-tutorial/tree/gh-pages

I'm removed the `hs blocks` commit. Is this alright with you?

**Comment by ranjitjhala** [comment]
Sorry for the delay! Merged!!!

**Comment by waddlaw** [comment]
Thanks!! :)

**Pull request merged**
